# https://typeof.net/Iosevka/customizer

[buildPlans.Vagari]
family = "Vagari"
spacing = "fontconfig-mono"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.Vagari.variants.design]
one = "no-base"
two = "curly-neck-serifless"
three = "flat-top-serifed"
four = "semi-open-non-crossing-serifless"
five = "upright-arched-serifed"
six = "straight-bar"
seven = "straight-serifed"
eight = "two-circles"
nine = "straight-bar"
zero = "tall-slashed-cutout"
capital-a = "round-top-serifless"
capital-b = "standard-serifless"
capital-c = "serifless"
capital-d = "standard-serifless"
capital-e = "serifless"
capital-g = "toothed-serifless-hooked"
capital-h = "serifless"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "crossing-baseline"
capital-r = "curly-open-serifless"
capital-s = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "straight-serifless"
capital-w = "straight-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "straight-serifless"
a = "single-storey-earless-corner-serifed"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
e = "rounded"
f = "serifless"
g = "single-storey-flat-hook-earless-corner"
h = "straight-serifless"
i = "serifless"
j = "flat-hook-serifless"
k = "straight-serifless"
l = "flat-tailed"
m = "earless-rounded-double-arch-short-leg-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "flat-hook"
u = "toothed-serifless"
v = "straight-serifless"
w = "rounded-vertical-sides-serifless"
x = "curly-serifless"
y = "curly-serifless"
z = "curly-serifless"
capital-eszet = "rounded-serifless"
lower-beta = "standard"
lower-theta = "diamond"
lower-chi = "semi-chancery-curly-serifed"
lower-psi = "serifed"
cyrl-a = "single-storey-tailed-serifed"
cyrl-ve = "cursive"
cyrl-capital-zhe = "curly"
cyrl-zhe = "curly"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "straight-top-left-and-bottom-right-serifed"
cyrl-ka = "straight-top-left-and-bottom-right-serifed"
cyrl-capital-en = "top-left-bottom-right-serifed"
cyrl-en = "top-left-bottom-right-serifed"
cyrl-capital-er = "closed-motion-serifed"
cyrl-er = "eared-motion-serifed"
cyrl-capital-u = "straight-turn-motion-serifed"
cyrl-u = "straight-turn-motion-serifed"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "round-tailed"
cyrl-capital-ya = "curly-serifed"
cyrl-ya = "straight-open-tailed-serifed"
tittle = "round"
diacritic-dot = "round"
punctuation-dot = "round"
braille-dot = "round"
asterisk = "hex-low"
underscore = "high"
caret = "medium"
ascii-grave = "straight"
ascii-single-quote = "raised-comma"
paren = "flat-arc"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
ampersand = "closed"
at = "fourfold"
dollar = "through"
percent = "rings-continuous-slash"
bar = "natural-slope"
pilcrow = "high"
micro-sign = "toothless-rounded-motion-serifed"
decorative-angle-brackets = "tall"
lig-ltgteq = "flat"
lig-neq = "more-slanted-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

  [buildPlans.Vagari.ligations]
  inherits = "purescript"

[buildPlans.Vagari.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Vagari.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.Vagari.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Vagari.weights.Light]
shape = 400
menu = 400
css = 400

[buildPlans.Vagari.weights.Regular]
shape = 500
menu = 500
css = 500

[buildPlans.Vagari.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Vagari.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Vagari.weights.ExtraBold]
shape = 800
menu = 800
css = 800